// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFkVlL-Ibx-3qXkW7SJ5TuAlJItEhIPjM',
    appId: '1:906803272367:web:a88eb801d22d26f03b925a',
    messagingSenderId: '906803272367',
    projectId: 'iq-profiler-mbpi',
    authDomain: 'iq-profiler-mbpi.firebaseapp.com',
    storageBucket: 'iq-profiler-mbpi.appspot.com',
    measurementId: 'G-82J1TQFVQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuZOzyHnFi5JDZJLU-f8qNhxdfm6bHMAc',
    appId: '1:906803272367:android:9a0c62b5dc2c70e03b925a',
    messagingSenderId: '906803272367',
    projectId: 'iq-profiler-mbpi',
    storageBucket: 'iq-profiler-mbpi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwC4N3IiBavkSViAMU1rQ5mRsCE7BAeto',
    appId: '1:906803272367:ios:11155f36338aca5d3b925a',
    messagingSenderId: '906803272367',
    projectId: 'iq-profiler-mbpi',
    storageBucket: 'iq-profiler-mbpi.appspot.com',
    iosBundleId: 'com.example.mbpiIq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwC4N3IiBavkSViAMU1rQ5mRsCE7BAeto',
    appId: '1:906803272367:ios:09ede8471809e1163b925a',
    messagingSenderId: '906803272367',
    projectId: 'iq-profiler-mbpi',
    storageBucket: 'iq-profiler-mbpi.appspot.com',
    iosBundleId: 'com.example.mbpiIq.RunnerTests',
  );
}
